# Generated by Django 3.2.16 on 2023-03-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietChart', '0002_diet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet',
            old_name='Friday',
            new_name='Breakfast',
        ),
        migrations.RenameField(
            model_name='diet',
            old_name='Monday',
            new_name='Days',
        ),
        migrations.RenameField(
            model_name='diet',
            old_name='Saturday',
            new_name='Dinner',
        ),
        migrations.RenameField(
            model_name='diet',
            old_name='Sunday',
            new_name='Lunch',
        ),
        migrations.RenameField(
            model_name='diet',
            old_name='Thursday',
            new_name='Snacks',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='Tuesday',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='Wednesday',
        ),
    ]
