# Generated by Django 3.2.16 on 2023-03-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietChart', '0003_auto_20230311_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='Breakfast',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='diet',
            name='Days',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='diet',
            name='Dinner',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='diet',
            name='Lunch',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='diet',
            name='Snacks',
            field=models.CharField(max_length=1000),
        ),
    ]
