# Generated by Django 3.2.16 on 2023-03-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietChart', '0004_auto_20230312_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='diet1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Days', models.CharField(max_length=1000)),
                ('Breakfast', models.CharField(max_length=1000)),
                ('Lunch', models.CharField(max_length=1000)),
                ('Snacks', models.CharField(max_length=1000)),
                ('Dinner', models.CharField(max_length=1000)),
            ],
        ),
    ]
