# Generated by Django 3.2.16 on 2023-03-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietChart', '0006_foodtracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtracker',
            name='Foods',
            field=models.CharField(max_length=1000),
        ),
    ]
