# Generated by Django 3.2.16 on 2023-03-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietChart', '0007_alter_foodtracker_foods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtracker',
            name='Quantity',
        ),
        migrations.AlterField(
            model_name='foodtracker',
            name='Carbs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='foodtracker',
            name='Fat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='foodtracker',
            name='Foods',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='foodtracker',
            name='Protien',
            field=models.IntegerField(null=True),
        ),
    ]
